### ISSUE TITLE
Feature Request: Eventstore to BigQuery or Redshit.

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/eventstore-interconnect#3]
Passing events to bigquery or any other 3rd party solution.

**Comment by AlexandreDecollas** [comment]
Do you mean reading on an event store and in place of writing to another one, writing on bigquery? or give the possibility to write on bigquery while processing original workflow? Can you explicit please?

**Comment by kodeine** [comment]
So right now our use case is to write events to big query so dashboards can use analytical queries on bq. We have our internal little app proxying events to bq. 

This package can be improved further to allow transports of choice so we can proxy events to any 3rd party. For example we allow array of transports to use, source to remote esdb, big query, redshift and even can be used for webhooks. Endless possibilities. This way events can be proxied realtime anywhere.

**Comment by AlexandreDecollas** [comment]
Hi @kodeine 

So to be sure to understand your need: 
In the workflow: 
1: an event appears on source eventstore
2: is validated
3: the event is copied to the destination eventstore. 

What you want is a hook that can be triggerd when the event is copied to eventstore (3) so then it can do something else with this event, like as you said beeing copied on any other place?

**Comment by AlexandreDecollas** [comment]
I've made a little PR, could you check with the example that it's what you wanted please?

**Comment by AlexandreDecollas** [comment]
After a conversation I had with my team, it seams that it's not the way it should work, you probably should more create an eventhandler that will transfert the event on the service you need. The purpose of the lib is only a copy past from an eventstore to another
